// sw.js: quest_log's service worker (generated by scripts/web-export.mjs; don't edit).
// Keeps a copy of every file of this build so the app works offline.
const CACHE = 'quest_log-3f2c66e4bfdf';
// The app's page as stored for offline use: the site root, which every host serves
// directly (some answer /index.html with a redirect, and browsers won't use a stored
// redirect to load a page).
const INDEX = '/quest_log/';
const FILES = [
  "/quest_log/",
  "/quest_log/_expo/static/js/web/entry-c9594bf56d9e48b95f99aaf87962d0aa.js",
  "/quest_log/assets/assets/fonts/JetBrainsMono-Bold.91852d9f8e40fac54b57e7624960f348.ttf",
  "/quest_log/assets/assets/fonts/JetBrainsMono-Medium.19d6e467fad4fbadeaf5df39effd83ad.ttf",
  "/quest_log/assets/assets/fonts/JetBrainsMono-Regular.e8e00f69f2ceb361f8d9fc48499ccba0.ttf",
  "/quest_log/assets/node_modules/expo-router/assets/arrow_down.017bc6ba3fc25503e5eb5e53826d48a8.png",
  "/quest_log/assets/node_modules/expo-router/assets/error.d1ea1496f9057eb392d5bbf3732a61b7.png",
  "/quest_log/assets/node_modules/expo-router/assets/file.19eeb73b9593a38f8e9f418337fc7d10.png",
  "/quest_log/assets/node_modules/expo-router/assets/forward.d8b800c443b8972542883e0b9de2bdc6.png",
  "/quest_log/assets/node_modules/expo-router/assets/pkg.ab19f4cbc543357183a20571f68380a3.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/back-icon-mask.0a328cd9c1afd0afe8e3b1ec5165b1b4.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/back-icon.35ba0eaec5a4f5ed12ca16fabeae451d.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55@2x.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55@3x.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55@4x.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/close-icon.808e1b1b9b53114ec2838071a7e6daa7.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/close-icon.808e1b1b9b53114ec2838071a7e6daa7@2x.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/close-icon.808e1b1b9b53114ec2838071a7e6daa7@3x.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/close-icon.808e1b1b9b53114ec2838071a7e6daa7@4x.png",
  "/quest_log/assets/node_modules/expo-router/assets/react-navigation/elements/search-icon.286d67d3f74808a60a78d3ebf1a5fb57.png",
  "/quest_log/assets/node_modules/expo-router/assets/sitemap.412dd9275b6b48ad28f5e3d81bb1f626.png",
  "/quest_log/assets/node_modules/expo-router/assets/unmatched.20e71bdf79e3a97bf55fd9e164041578.png",
  "/quest_log/favicon.ico",
  "/quest_log/icons/apple-touch-icon.png",
  "/quest_log/icons/icon-192.png",
  "/quest_log/icons/icon-512.png",
  "/quest_log/icons/maskable-512.png",
  "/quest_log/index.html",
  "/quest_log/manifest.json"
];

// Install: download this build's files; take over without waiting for old tabs to close.
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

// Activate: drop the copies of older builds.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('quest_log-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Fetch: pages try the network first (to pick up a new version) and fall back to the
// stored app offline; every other file comes from the store first (file names change
// with each build, so a stored file is never stale).
self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() =>
        caches.match(INDEX).then((hit) => (hit && hit.redirected ? new Response(hit.body, { status: 200, headers: hit.headers }) : hit)),
      ),
    );
    return;
  }
  event.respondWith(caches.match(request).then((hit) => hit || fetch(request)));
});
