// scripts/web-export.mjs: builds the web version / iPhone PWA into web-dist/.
//
// Usage: node scripts/web-export.mjs            (site served at /)
//        QUESTLOG_WEB_BASE=/quest_log node scripts/web-export.mjs   (GitHub Pages)
//
// Steps:
//   1. `expo export -p web` (single-page app; public/ is copied in),
//   2. fill in %BASE_URL% in index.html (the site's path),
//   3. 404.html = index.html, so GitHub Pages serves the app on any deep link,
//   4. .nojekyll, or GitHub Pages hides the `_expo` folder (leading underscore),
//   5. sw.js: a service worker that stores every file of this build, so the
//      app opens and runs with no connection. Its cache name is a hash of the
//      files, so each new build replaces the old copy on the next launch.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { copyFileSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'web-dist');
const base = (process.env.QUESTLOG_WEB_BASE ?? '').replace(/\/$/, '');

// 1. Export (Expo reads QUESTLOG_WEB_BASE through app.config.ts for the bundle paths).
execFileSync('npx', ['expo', 'export', '-p', 'web', '--output-dir', 'web-dist', '--clear'], { cwd: root, stdio: 'inherit' });

// 2. The page template's site path.
const indexPath = join(out, 'index.html');
writeFileSync(indexPath, readFileSync(indexPath, 'utf8').replaceAll('%BASE_URL%', base));

// 3–4. GitHub Pages: deep links and the _expo folder.
copyFileSync(indexPath, join(out, '404.html'));
writeFileSync(join(out, '.nojekyll'), '');

// 5. Every file of the build, as site URLs (except the files the worker shouldn't keep).
const SKIP = new Set(['sw.js', '404.html', '.nojekyll', 'metadata.json']);
const files = [];
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (!SKIP.has(relative(out, p))) files.push(relative(out, p).split('\\').join('/'));
  }
};
walk(out);
files.sort();
const hash = createHash('sha256');
for (const f of files) hash.update(f).update(readFileSync(join(out, f)));
const version = hash.digest('hex').slice(0, 12);
const urls = [`${base}/`, ...files.map((f) => `${base}/${f}`)];

writeFileSync(
  join(out, 'sw.js'),
  `// sw.js: quest_log's service worker (generated by scripts/web-export.mjs; don't edit).
// Keeps a copy of every file of this build so the app works offline.
const CACHE = 'quest_log-${version}';
const INDEX = '${base}/index.html';
const FILES = ${JSON.stringify(urls, null, 2)};

// Install: download this build's files; take over without waiting for old tabs to close.
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

// Activate: drop the copies of older builds.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('quest_log-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Fetch: pages try the network first (to pick up a new version) and fall back to the
// stored app offline; every other file comes from the store first (file names change
// with each build, so a stored file is never stale).
self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.match(INDEX)));
    return;
  }
  event.respondWith(caches.match(request).then((hit) => hit || fetch(request)));
});
`,
);
console.log(`web-dist ready: ${files.length} files, base "${base || '/'}", service worker ${version}`);
